### ISSUE TITLE
搭建网站中的一些问题

### ISSUE THREAD

**Issue by leonardo0004** [233sec/laravel-src#1]
您好！我在搭建完成后发现他的css和js无法正确的加载，没有找到您框架的网站路由是写在哪里的。。能否方便告知一下，还有就是超管的默认密码是多少，如果不方便在此回复可以回复邮件，我的邮件是313833500@qq.com

**Comment by xiaohuilam** [comment]
如果是本地环境（无法使用cdn请将.env中APP_ENV更改为local或dev）
如果是生产环境请更改下面这几项
APP_URL=http://security.233sec.com
CDN_ASSETS_ENABLE=false
CDN_ASSETS_DOMAIN=https://security.233cdn.com

**Comment by leonardo0004** [comment]
我在本地环境测试，我已经将.env中的APP_URL=CDN_ASSETS_ENABLE=CDN_ASSETS_DOMAIN=三项功能全部删除了，并且APP_ENV=local，在本地添加了hosts进行访问还是无法加载正确的css和js，我是将程序放置在/var/www/html中的

**Comment by xiaohuilam** [comment]
本系统所用框架的路由入口文件为public/index.php 排查下是否因此导致？

**Comment by xiaohuilam** [comment]
本地环境是支持php artisan serve启动服务的，可以用这个

**Comment by xiaohuilam** [comment]
经沟通确认已解决，这个issue先关掉
